spring:
  application:
    name: DOSW_ParcialT2_AndresVivas

  datasource:
    url: jdbc:postgresql://localhost:5432/dosw_parcial
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    edu.dosw.parcial: DEBUG
    org.springframework.security: INFO